package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SeatAllocationController {
	@FXML
	private TextField NoOfSeats;
	@FXML
	private Label TotalPrice;
	@FXML
	private Button btnbooknow;
	@FXML
	private Label TicketBookStatus;
	@FXML
	private Button back;
	@FXML
	private Button btntotalprice;
	@FXML
	private Button btnLOGOUT;

	// Event Listener on Button[#booknow].onAction
	@FXML
	public void booknow(ActionEvent booknow) {
		// TODO Autogenerated
		if(booknow.getSource()==btnbooknow) {
			TicketBookStatus.setText("Ticket Booked successfully");}
	}
	// Event Listener on Button[#back].onAction
	@FXML
	public void back(ActionEvent event)  throws IOException {
		// TODO Autogenerated
			Stage primaryStage = new Stage();
			Parent root = FXMLLoader.load(getClass().getResource("/view/Booking.fxml"));
			Scene scene = new Scene(root);
			//scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.show();}
	
	public void logout(ActionEvent event)throws IOException
	{
		Stage primaryStage = new Stage();
		Parent root = FXMLLoader.load(getClass().getResource("/view/Login.fxml"));
		Scene scene = new Scene(root);
		//scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
		primaryStage.setScene(scene);
		primaryStage.show();
		
	}
	
	// Event Listener on Button[#totalprice].onAction
	@FXML
	public void totalprice(ActionEvent totalprice) {
		// TODO Autogenerated
		if(totalprice.getSource()==btntotalprice)
		{
			if(NoOfSeats.getText().equals("1"))
		{
				TotalPrice.setText("Price of 1 ticket is $20");
		}
			else if(NoOfSeats.getText().equals("2"))
				
			{
					TotalPrice.setText("Price of 2 ticket is $40");
			}
			else if(NoOfSeats.getText().equals("3"))
				
			{
					TotalPrice.setText("Price of 3 ticket is $60");
			}
			else if(NoOfSeats.getText().equals("4"))
				
			{
					TotalPrice.setText("Price of 4 ticket is $80");
			}
			else if(NoOfSeats.getText().equals("5"))
				
			{
					TotalPrice.setText("Price of 5 ticket is $100");
			}
			else if(NoOfSeats.getText().equals("6"))
				
			{
					TotalPrice.setText("Price of 6 ticket is $120");
			}
			else if(NoOfSeats.getText().equals("7"))
				
			{
					TotalPrice.setText("Price of 7 ticket is $140");
			}
			else if(NoOfSeats.getText().equals("8"))
				
			{
					TotalPrice.setText("Price of 8 ticket is $160");
			}
			else if(NoOfSeats.getText().equals("9"))
				
			{
					TotalPrice.setText("Price of 9 ticket is $180");
			}
			else if(NoOfSeats.getText().equals("10"))
				
			{
					TotalPrice.setText("Price of 10 ticket is $200");
			}
		}
	}
}
